# Generated by Django 5.1.1 on 2024-11-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_is_flash_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shipping_address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
    ]
